version: 1.0.{build}

image: Visual Studio 2017


before_build:
- nuget restore

build:
  verbosity: minimal
  
platform: Any CPU

artifacts:
  - path: %APPVEYOR_BUILD_FOLDER%\src\bin\$(configuration)\*.*
    name: $(configuration).zip
