version: 1.0.{build}

image: Visual Studio 2017

configuration: Debug

before_build:
- nuget restore

build:
  verbosity: minimal
  
platform: Any CPU

artifacts:
  - path: src\bin\$(configuration)
    name: $(configuration).zip
