version: 1.0.{build}

image: Visual Studio 2017


before_build:
- nuget restore

build:
  verbosity: minimal
  
platform: Any CPU

artifacts:
  - path: C:\projects\ks2-drive\src\$(configuration)\*.*
    name: $(configuration).zip
